# Nombre del microservicio
spring.application.name=events

# Puerto donde se levanta
server.port=8080

# CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)

# URL de conexión. 'athenet_events_db'
spring.datasource.url=jdbc:postgresql://localhost:5432/athenet_events_db

spring.datasource.username=user_athenet

spring.datasource.password=password_athenet

# Driver de conexión
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola (terminal) las consultas SQL que Spring Boot hace por detrás
spring.jpa.show-sql=true

# Formatea el SQL en la consola para que sea legible y ordenado
spring.jpa.properties.hibernate.format_sql=true

# Le indica a Hibernate que debe generar código SQL optimizado para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect