# Nombre del microservicio
spring.application.name=events

# Puerto donde se levanta
server.port=8080

# CONFIGURACIÓN DE BASE DE DATOS (PostgreSQL)

# URL de conexión. 'athenet_events_db' es el nombre que debe tener tu BD en pgAdmin/DBeaver
spring.datasource.url=jdbc:postgresql://localhost:5432/athenet_events_db

# Tu usuario de base de datos local (por defecto suele ser 'postgres')
spring.datasource.username=postgres

# Tu contraseña de base de datos local
spring.datasource.password=postgres

# Driver de conexión
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# "update": Lee tus clases @Entity y crea/actualiza las tablas automáticamente sin borrar los datos.
# (Nota: En producción real esto suele cambiarse a "validate").
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola (terminal) las consultas SQL que Spring Boot hace por detrás
spring.jpa.show-sql=true
# Formatea el SQL en la consola para que sea legible y ordenado
spring.jpa.properties.hibernate.format_sql=true

# Le indica a Hibernate que debe generar código SQL optimizado para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect